name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: v1.33.0
        id: install
      - name: Validate yaml file
        env:
          MY_PATH: ./
        run: echo "$MY_PATH"
        run: kubectl apply --dry-run -f ../../nginx-deployment.yaml
