name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v4
        with:
          version: default
        id: install
      - name: Validate yaml file
        run: kubectl apply --dry-run -f ../../nginx-deployment.yaml
